from math import pi
# print()
# square=float(input("What is the length of a side of the square? "))
# print(f"The area of the square is: {square**2}")
# print()
# length = float(input("What is the length of rectangle? "))
# width = float(input("What is the width of the rectangle? "))
# print(f"The area of the rectangle is: {length*width}")
# print()
# radius = float(input("What is the radius of the circle? "))
# print(f"The area of the circle is: {pi*radius**2:.1f}")

print()
lenght=float(input("What is the length (cm)? "))
lenght_cm = lenght * 10**-2
print(f"The area of the square is: {lenght**2} cm^2")
print(f"The area of the square is: {lenght_cm**2} m^2")
print()
print(f"The area of the circle is: {pi*lenght**2:.1f} cm^2")
print(f"The area of the circle is: {pi*lenght_cm**2:.1f} m^2")
print()
print(f"The volume of the cube is: {lenght**3} cm^3")
print(f"The volume of the cube is: {lenght_cm**3} m^3")
print()
print(f"The volume of the sphere is: {(4/3)*pi*lenght**3:.1f} cm^3")
print(f"The volume of the sphere is: {(4/3)*pi*lenght_cm**3:.1f} m^3")
print()